version: "3.9"

services:
  db:
    image: postgres:15
    platform: linux/arm64
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: budget_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    platform: linux/arm64
    container_name: backend
    env_file:
      - ./server/.env
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./server:/app            # your code
      - /app/node_modules        # container-managed node_modules (prevents host override)

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    platform: linux/arm64
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"

volumes:
  db-data:
