version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: budget_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./server
    container_name: backend
    env_file:
    - ./server/.env
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "5555:5555"

  frontend:
    build: ./client
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:80"  
volumes:
  db-data:
